# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa932502354b50387c0d5c8cdec915b781282614905101c00343ac0624d500899f5f04d3739a57f6b4b4cc1d1e4c021b9b1d7a5f579c1aa14c681c06b3a5e03

test:
  secret_key_base: be481235c924433c4ae0e64dcdd35e5c797b4386960051efacff26174ee4c756bdb45c99862d57de667804282dde5cff763c3a48354ffed861f31de718ee713d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
